export type H = {
  Address: string | null,
  ApiUpdateAt: string | null,
  Baths: number | null,
  BathsFull: number | null,
  BathsHalf: number | null,
  Beds: number | null,
  Branding: string | null,
  City: string | null,
  County: string | null,
  Garage: number | null,
  Latitude: number | null,
  ListDate: string | null,
  ListPrice: number | null,
  ListingId: string | null,
  Longitude: number | null,
  LotSqft: number | null,
  PermLink: string | null,
  Photos: string[] | null,
  PostalCode: string | null,
  PropertyId: string | null,
  PropertyType: string | null,
  Sqft: number | null,
  State: string | null,
  StateCode: string | null,
  Status: string | null,
  Stories: number | null,
  Tags: string[] | null,
  YearBuilt: number | null,
}

