import type { NextPage } from 'next'
import Head from 'next/head'
import { useSnapshot } from 'valtio'
import { homeStore } from './_app'




const Home: NextPage = () => {
 

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{height: '100vh'}}>
        This is the home page 
      </main>
    </div>
  )
}

export default Home
